config/routes.rb
Debate::Application.routes.draw do

  get "home/index"

  get 'login', :to => 'twitter#login', :as => "login"
  get 'logout', :to => 'twitter#logout', :as => "logout"

  get "twitter/after_login"

  resources :debate_questions, :only => [:index, :show, :create], :shallow => true do
    resources :comments, :only => [:create, :index] do
      resource :comment_votes, :only => [:create]
    end

    resources :debate_votes, :only => [:create]
  end

  root :to => "home#index"

end

app/models/debate_question.rb
class DebateQuestion < ActiveRecord::Base
  self.per_page = 20

  belongs_to :user
  has_many :debate_votes
  has_many :comments, :order => "created_at DESC"

  has_many :debate_yes_votes, :class_name => "DebateVote", :conditions => {:current_vote => 1}
  has_many :debate_no_votes, :class_name => "DebateVote", :conditions => {:current_vote => -1}
  has_many :debate_neutral_votes, :class_name => "DebateVote", :conditions => {:current_vote => 0}

  attr_accessible :body, :yes_count, :no_count, :neutral_count, :user_id

  validates :body, :presence => true, :length => {:within => 3..256}
  validates :user_id, :presence => true

  scope :top_debates, select("(yes_count + no_count  + neutral_count) as votes, debate_questions.*").order("votes DESC")
  scope :recent_debates, order("created_at DESC")

  def self.all_debates(sort = :top)
    case sort
      when :top
        top_debates
      when :recent
        recent_debates
      else
        recent_debates
    end
  end

  def uniq_votes
    DebateVote.uniq_votes.where(:debate_question_id => self.id)
  end

  def vote?(user_id)
    if user_vote(user_id)
      @user_vote.vote
    else
      nil
    end
  end

  def user_vote(user_id)
    @user_vote ||= debate_votes.where(:user_id => user_id).last
  end

  def analytics_data
    result = analytics_vote_count
    analytics_data_hash = {}
    [:yes, :no, :neutral].each do |vote|
      analytics_data_hash[vote] = result[vote] unless result[vote].empty?
    end

    analytics_data_hash
  end

  def recounting
    result = DebateVote.sub_query(uniq_votes).count(:id, :group => :current_vote)
    self.update_attributes(:yes_count => result[DebateVote::YES] || 0,
                           :no_count => result[DebateVote::NO] || 0,
                           :neutral_count => result[DebateVote::NEUTRAL] || 0)
  end

  def winner
    max_vote = [yes_count, no_count, neutral_count].max
    case max_vote
      when yes_count
        "positive"
      when no_count
        "negative"
      when neutral_count
        "neutral"
    end
  end

  private

  def analytics_vote_count
    data_array = {:yes => [], :no => [], :neutral => []}

    DebateVote.sub_query(uniq_votes).select(" UNIX_TIMESTAMP(DATE(debate_votes.created_at))*1000 as date,
                                              count(debate_votes.current_vote) as count_by_day,
                                              debate_votes.current_vote").
        group("DATE(debate_votes.created_at), debate_votes.current_vote").each do |data|

      count = [data.date.to_i, data.count_by_day.to_i]

      case data.current_vote.to_i
        when -1
          data_array[:no] << count
        when 0
          data_array[:neutral] << count
        when 1
          data_array[:yes] << count
      end
    end

    data_array
  end

end

# == Schema Information
#
# Table name: debate_questions
#
#  id            :integer(4)      not null, primary key
#  user_id       :integer(4)
#  body          :string(255)     not null
#  yes_count     :integer(4)      default(0)
#  no_count      :integer(4)      default(0)
#  neutral_count :integer(4)      default(0)
#  created_at    :datetime
#  updated_at    :datetime
#

app/controllers/debate_questions_controller.rb
class DebateQuestionsController < ApplicationController

  before_filter :is_logged?, :except => [:index, :show]

  def index
    @debates = DebateQuestion.all_debates(:recent).paginate(:page => params[:page])
  end

  def show
    @debate_question = DebateQuestion.includes(:comments => :comment_votes).find(params[:id])
    @comments = @debate_question.comments.paginate(:page => params[:page])
    @analytics_data = @debate_question.analytics_data
  end

  def create
    debate_question = current_user.debate_questions.create!(params[:debate_question])

    push_notice_message t(:debate_created)
    redirect_to debate_question

  rescue StandardError => ex
    push_error_message t(:debate_not_valid)
    redirect_to root_path
  end

end

app/helpers/debate_questions_helper.rb
module DebateQuestionsHelper
end

app/views/debate_questions/_analytics.html.erb
<script>
   new Analytics(<%= analytics_data.to_json.html_safe %>);
</script>
<div id="placeholder_by_debate_analytics" style="margin-left:20px;width:860px;height:300px;"></div>
<div id="overview_by_debate_analytics" style="margin-left:20px;margin-top:20px;width:860px;height:100px"></div>

app/views/debate_questions/_debate_question.html.erb
<div id="debate">
  <div class="article">
    <p><%= link_to debate_question.body, debate_question_path(debate_question) %></p>

    <div class="votes">
      <ul>
        <li>
          <p class="yes"> <%= t('yes_votes') %>: <%= debate_question.yes_count %></p>
        </li>
        <li>
          <p class="neut"><%= t('neutral_votes') %>: <%= debate_question.neutral_count %></p>
        </li>
        <li>
          <p class="no"><%= t('no_votes') %>: <%= debate_question.no_count %></p>
        </li>
      </ul>
    </div>
    <a class="more" href="#">View debate</a>
    <%= link_to "View debate", debate_question_path(debate_question), :class => "more" %>
  </div>
</div>

app/views/debate_questions/_new_debate_question.html.erb
<a href="#dialog" name="modal" class="all_button">New Debate</a>

<div id="boxes">

  <div id="dialog" class="window">
    <b>Adding new question</b>

    <!-- close button is defined as close class -->
    <a href="#"><div class="close"></div></a>

    <%= form_for (DebateQuestion.new) do |form| %>
        <div id="label_comment">
          <%= form.label "Your question:" %>
        </div>
        <div id="text_comment">
          <%= form.text_area :body, :size => "51x8" %>
        </div>

        <div id="button_comment">
          <%= form.submit %>
        </div>
    <% end %>

  </div>


  <!-- Do not remove div#mask, because you'll need it to fill the whole screen -->
  <div id="mask"></div>
</div>

app/views/debate_questions/_vote_buttons.erb
<ul>
  <li>
    <%= button_to t('button.yes_counter', :count => debate.yes_count), debate_question_debate_votes_path(debate.id, :vote => 1),
                  :method => :post, :remote => true, :disabled => voted?(debate, :yes), :class => "positive" %>
  </li>
  <li>
    <%= button_to t('button.neutral_counter', :count => debate.neutral_count), debate_question_debate_votes_path(debate.id, :vote => 0),
                  :method => :post, :remote => true, :disabled => voted?(debate, :neutral), :class => "neutral" %>
  </li>
  <li>
  <%= button_to t('button.no_counter', :count => debate.no_count), debate_question_debate_votes_path(debate.id, :vote => -1),
  :method => :post, :remote => true, :disabled => voted?(debate, :no), :class => "negative" %>
  </li>
</ul>

app/views/debate_questions/index.html.erb
<br>

<%= will_paginate @debates %>

<%= render @debates %>

<%= will_paginate @debates %>

app/views/debate_questions/show.html.erb
<h1>DebateQuestion</h1>
<div id="analytics" style="display:none;">
  <%= render :partial => "debate_questions/analytics", :locals => {:analytics_data => @analytics_data} %>
</div>


<div class="question_area ">
  <p><%= @debate_question.body %></p>

  <% if controller.authorized? %>
  <div id="vote_buttons">
    <%= render :partial => "debate_questions/vote_buttons", :locals => {:debate => @debate_question} %>
  </div>
  <% end %>
</div>

<h3><span><%= t('comments') %>:</span></h3>

<div id="comments">
  <%= render 'comments/list' %>
</div>

<% if controller.authorized? %>
<h3><span><%= t('new_comment') %></span></h3>
<%= form_for (Comment.new, :url => debate_question_comments_path(@debate_question), :remote => true) do |f| %>
    <%= f.hidden_field :debate_question_id, :value => @debate_question.id %>
    <div id="new_comment">
      <div id="label_comment"><%= f.label "Your comment:"%></div>
      <div id="text_comment"><%= f.text_area :body, :size => "90x3" %></div>
      <div id="button_comment"><%= f.submit %></div>
    </div>
<% end %>
<% end %>