config/routes.rb
Debate::Application.routes.draw do

  get "home/index"

  get 'login', :to => 'twitter#login', :as => "login"
  get 'logout', :to => 'twitter#logout', :as => "logout"

  get "twitter/after_login"

  resources :debate_questions, :only => [:index, :show, :create], :shallow => true do
    resources :comments, :only => [:create, :index] do
      resource :comment_votes, :only => [:create]
    end

    resources :debate_votes, :only => [:create]
  end

  root :to => "home#index"

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <ul>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "All Debates", debate_questions_path  %>
    </li>
  </ul>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <h1><span><a href="<%=root_path %>">Our <span id="color">Debate</span> Project</a></span></h1>

  <p id="about">Lorem ipsum dolor sit amet</p>
  <!--===========================================================================================-->
  <% if controller.authorized? %>
      <div id="user_section">
        <div id="greeting">
          <h3>
            <%= t('welcome') %>
            <%= link_to controller.current_user.screen_name, controller.current_user.profile_url, :class => "welcome_link" %>
          </h3>
        </div>
      </div>
  <% end %>

  <div id="menu-box">
    <ul id="web">
      <% if controller.authorized? %>
          <li>
            <%= link_to t(:logout), logout_url, {:id => "logout"} %>
          </li>
    <% else %>
          <li>
            <%= link_to image_tag("/images/twitter_button.gif"), login_url, :id => "twitter_login_but" %>
          </li>
    <% end %>

      <li>
        <%= link_to t('all_debates'), debate_questions_path %>
      </li>
      <li>
        <%= link_to t('home'), root_url %>
      </li>
    </ul>

    <div id="system_message"> <%= system_messages %> </div>
  </div>
</div>

app/views/layouts/_sys_messages.erb
<% session[:system_message][:notice].each do |msg| %>
    <div class="notice"> <%= msg %> </div> </br>
<% end %>

<% session[:system_message][:error].each do |msg| %>
    <div class="error"> <%= msg %> </div> </br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= t('debates') %>
  </title>
  <%= yield :head %>
  <%= stylesheet_link_tag "default" %>
  <%= stylesheet_link_tag('jquery.jqplot.min.css') %>

  <%= javascript_include_tag  :defaults, :jqplot, 'pop-up' %>
  <%#%>
  <script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>

  <%= csrf_meta_tag %>
</head>
<body id="top">

<!--<div id="top_bar"></div>-->

<div id="wrapper">
  <%= render :partial => "layouts/header" %>
  <div class="page">
    <%= yield %>
  </div>
  <%= render :partial => "layouts/footer" %>
</div>

</body>
</html>